services:
  nginx:
    depends_on:
      - app
      - backend
    restart: always
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/ssl/cert.pem:/etc/nginx/ssl/cert.pem
      - /etc/nginx/ssl/key.pem:/etc/nginx/ssl/key.pem

  app:
    image: ghcr.io/hampuslundblad/edh-mm-app:main
    ports:
      - "3000:3000"
  backend:
    image: ghcr.io/hampuslundblad/edh-mm-backend:main
    volumes:
      - edhmm-db:/data
    ports:
      - "5000:5000"
volumes:
  edhmm-db:
